AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Description: infrastructure cloudformation script
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
      Timeout: 30  # in seconds
Parameters:
  TargetEnvr:
    Type: String
Resources:
  ########################################
  ##### AWS RDS and related services #####
  ########################################
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub celestial-studio-${TargetEnvr}-subnet-group
      DBSubnetGroupDescription: Subnet Group
      SubnetIds:
      - subnet-0608d15aefe1735ec
      - subnet-0deab5ad0e63af50d
      - subnet-03ac3380f6870bb72
  RdsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: 8.4.5
      MultiAZ: false
      DBInstanceIdentifier: !Sub celestial-studio-mysql-${TargetEnvr}
      MasterUsername: admin
      MasterUserPassword: !Sub '{{resolve:ssm:mysql-${TargetEnvr}-admin-pwd}}'
      DBInstanceClass: db.t4g.micro
      StorageType: gp2
      AllocatedStorage: 20
      PubliclyAccessible: true
      DBSubnetGroupName: !Ref RdsSubnetGroup
  #######################
  ######### SQS #########
  #######################
  PolarisLoggerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub polaris-${TargetEnvr}-logger-queue
Outputs:
  DbEndpoint:
    Value: !GetAtt RdsDatabase.Endpoint.Address
    Export:
      Name: !Sub celestial-studio-${TargetEnvr}-db-endpoint
  PolarisLoggerQueueArn:
    Value: !GetAtt PolarisLoggerQueue.Arn
    Export:
      Name: !Sub polaris-${TargetEnvr}-logger-queue-arn
  PolarisLoggerQueueUrl:
    Value: !GetAtt PolarisLoggerQueue.QueueUrl
    Export:
      Name: !Sub polaris-${TargetEnvr}-logger-queue-url